//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IndustryApp.Droid.WSIndustryApp {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseBase))]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeUsuarioPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeUsuarioPorCorreoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarContactoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeContactosPorIdUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeContactoPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeAllExposOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeExpoPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeEventosPorIdExpoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeEventoPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeStandsPorIdExpoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeStandPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeSponsorsPorIdExpoOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraeSponsorPorIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = "http://localhost:57116/WebService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event RegistrarUsuarioCompletedEventHandler RegistrarUsuarioCompleted;
        
        /// <remarks/>
        public event TraeUsuarioPorIdCompletedEventHandler TraeUsuarioPorIdCompleted;
        
        /// <remarks/>
        public event TraeUsuarioPorCorreoCompletedEventHandler TraeUsuarioPorCorreoCompleted;
        
        /// <remarks/>
        public event RegistrarContactoCompletedEventHandler RegistrarContactoCompleted;
        
        /// <remarks/>
        public event TraeContactosPorIdUsuarioCompletedEventHandler TraeContactosPorIdUsuarioCompleted;
        
        /// <remarks/>
        public event TraeContactoPorIdCompletedEventHandler TraeContactoPorIdCompleted;
        
        /// <remarks/>
        public event TraeAllExposCompletedEventHandler TraeAllExposCompleted;
        
        /// <remarks/>
        public event TraeExpoPorIdCompletedEventHandler TraeExpoPorIdCompleted;
        
        /// <remarks/>
        public event TraeEventosPorIdExpoCompletedEventHandler TraeEventosPorIdExpoCompleted;
        
        /// <remarks/>
        public event TraeEventoPorIdCompletedEventHandler TraeEventoPorIdCompleted;
        
        /// <remarks/>
        public event TraeStandsPorIdExpoCompletedEventHandler TraeStandsPorIdExpoCompleted;
        
        /// <remarks/>
        public event TraeStandPorIdCompletedEventHandler TraeStandPorIdCompleted;
        
        /// <remarks/>
        public event TraeSponsorsPorIdExpoCompletedEventHandler TraeSponsorsPorIdExpoCompleted;
        
        /// <remarks/>
        public event TraeSponsorPorIdCompletedEventHandler TraeSponsorPorIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuarioResponse RegistrarUsuario(AddNewUsuarioRequest request) {
            object[] results = this.Invoke("RegistrarUsuario", new object[] {
                        request});
            return ((UsuarioResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarUsuarioAsync(AddNewUsuarioRequest request) {
            this.RegistrarUsuarioAsync(request, null);
        }
        
        /// <remarks/>
        public void RegistrarUsuarioAsync(AddNewUsuarioRequest request, object userState) {
            if ((this.RegistrarUsuarioOperationCompleted == null)) {
                this.RegistrarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarUsuarioOperationCompleted);
            }
            this.InvokeAsync("RegistrarUsuario", new object[] {
                        request}, this.RegistrarUsuarioOperationCompleted, userState);
        }
        
        private void OnRegistrarUsuarioOperationCompleted(object arg) {
            if ((this.RegistrarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarUsuarioCompleted(this, new RegistrarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TraeUsuarioPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuarioResponse TraeUsuarioPorId(int Id) {
            object[] results = this.Invoke("TraeUsuarioPorId", new object[] {
                        Id});
            return ((UsuarioResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TraeUsuarioPorIdAsync(int Id) {
            this.TraeUsuarioPorIdAsync(Id, null);
        }
        
        /// <remarks/>
        public void TraeUsuarioPorIdAsync(int Id, object userState) {
            if ((this.TraeUsuarioPorIdOperationCompleted == null)) {
                this.TraeUsuarioPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeUsuarioPorIdOperationCompleted);
            }
            this.InvokeAsync("TraeUsuarioPorId", new object[] {
                        Id}, this.TraeUsuarioPorIdOperationCompleted, userState);
        }
        
        private void OnTraeUsuarioPorIdOperationCompleted(object arg) {
            if ((this.TraeUsuarioPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeUsuarioPorIdCompleted(this, new TraeUsuarioPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TraeUsuarioPorCorreo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsuarioResponse TraeUsuarioPorCorreo(string correo) {
            object[] results = this.Invoke("TraeUsuarioPorCorreo", new object[] {
                        correo});
            return ((UsuarioResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TraeUsuarioPorCorreoAsync(string correo) {
            this.TraeUsuarioPorCorreoAsync(correo, null);
        }
        
        /// <remarks/>
        public void TraeUsuarioPorCorreoAsync(string correo, object userState) {
            if ((this.TraeUsuarioPorCorreoOperationCompleted == null)) {
                this.TraeUsuarioPorCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeUsuarioPorCorreoOperationCompleted);
            }
            this.InvokeAsync("TraeUsuarioPorCorreo", new object[] {
                        correo}, this.TraeUsuarioPorCorreoOperationCompleted, userState);
        }
        
        private void OnTraeUsuarioPorCorreoOperationCompleted(object arg) {
            if ((this.TraeUsuarioPorCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeUsuarioPorCorreoCompleted(this, new TraeUsuarioPorCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarContacto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ContactoResponse RegistrarContacto(AddNewContactoRequest request) {
            object[] results = this.Invoke("RegistrarContacto", new object[] {
                        request});
            return ((ContactoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarContactoAsync(AddNewContactoRequest request) {
            this.RegistrarContactoAsync(request, null);
        }
        
        /// <remarks/>
        public void RegistrarContactoAsync(AddNewContactoRequest request, object userState) {
            if ((this.RegistrarContactoOperationCompleted == null)) {
                this.RegistrarContactoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarContactoOperationCompleted);
            }
            this.InvokeAsync("RegistrarContacto", new object[] {
                        request}, this.RegistrarContactoOperationCompleted, userState);
        }
        
        private void OnRegistrarContactoOperationCompleted(object arg) {
            if ((this.RegistrarContactoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarContactoCompleted(this, new RegistrarContactoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TraeContactosPorIdUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ContactosResponse TraeContactosPorIdUsuario(int idUsuario) {
            object[] results = this.Invoke("TraeContactosPorIdUsuario", new object[] {
                        idUsuario});
            return ((ContactosResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TraeContactosPorIdUsuarioAsync(int idUsuario) {
            this.TraeContactosPorIdUsuarioAsync(idUsuario, null);
        }
        
        /// <remarks/>
        public void TraeContactosPorIdUsuarioAsync(int idUsuario, object userState) {
            if ((this.TraeContactosPorIdUsuarioOperationCompleted == null)) {
                this.TraeContactosPorIdUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeContactosPorIdUsuarioOperationCompleted);
            }
            this.InvokeAsync("TraeContactosPorIdUsuario", new object[] {
                        idUsuario}, this.TraeContactosPorIdUsuarioOperationCompleted, userState);
        }
        
        private void OnTraeContactosPorIdUsuarioOperationCompleted(object arg) {
            if ((this.TraeContactosPorIdUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeContactosPorIdUsuarioCompleted(this, new TraeContactosPorIdUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TraeContactoPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ContactoResponse TraeContactoPorId(int id) {
            object[] results = this.Invoke("TraeContactoPorId", new object[] {
                        id});
            return ((ContactoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TraeContactoPorIdAsync(int id) {
            this.TraeContactoPorIdAsync(id, null);
        }
        
        /// <remarks/>
        public void TraeContactoPorIdAsync(int id, object userState) {
            if ((this.TraeContactoPorIdOperationCompleted == null)) {
                this.TraeContactoPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeContactoPorIdOperationCompleted);
            }
            this.InvokeAsync("TraeContactoPorId", new object[] {
                        id}, this.TraeContactoPorIdOperationCompleted, userState);
        }
        
        private void OnTraeContactoPorIdOperationCompleted(object arg) {
            if ((this.TraeContactoPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeContactoPorIdCompleted(this, new TraeContactoPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TraeAllExpos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExposResponse TraeAllExpos() {
            object[] results = this.Invoke("TraeAllExpos", new object[0]);
            return ((ExposResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TraeAllExposAsync() {
            this.TraeAllExposAsync(null);
        }
        
        /// <remarks/>
        public void TraeAllExposAsync(object userState) {
            if ((this.TraeAllExposOperationCompleted == null)) {
                this.TraeAllExposOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeAllExposOperationCompleted);
            }
            this.InvokeAsync("TraeAllExpos", new object[0], this.TraeAllExposOperationCompleted, userState);
        }
        
        private void OnTraeAllExposOperationCompleted(object arg) {
            if ((this.TraeAllExposCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeAllExposCompleted(this, new TraeAllExposCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TraeExpoPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExpoResponse TraeExpoPorId(int idExpo) {
            object[] results = this.Invoke("TraeExpoPorId", new object[] {
                        idExpo});
            return ((ExpoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TraeExpoPorIdAsync(int idExpo) {
            this.TraeExpoPorIdAsync(idExpo, null);
        }
        
        /// <remarks/>
        public void TraeExpoPorIdAsync(int idExpo, object userState) {
            if ((this.TraeExpoPorIdOperationCompleted == null)) {
                this.TraeExpoPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeExpoPorIdOperationCompleted);
            }
            this.InvokeAsync("TraeExpoPorId", new object[] {
                        idExpo}, this.TraeExpoPorIdOperationCompleted, userState);
        }
        
        private void OnTraeExpoPorIdOperationCompleted(object arg) {
            if ((this.TraeExpoPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeExpoPorIdCompleted(this, new TraeExpoPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TraeEventosPorIdExpo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EventosResponse TraeEventosPorIdExpo(int idExpo) {
            object[] results = this.Invoke("TraeEventosPorIdExpo", new object[] {
                        idExpo});
            return ((EventosResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TraeEventosPorIdExpoAsync(int idExpo) {
            this.TraeEventosPorIdExpoAsync(idExpo, null);
        }
        
        /// <remarks/>
        public void TraeEventosPorIdExpoAsync(int idExpo, object userState) {
            if ((this.TraeEventosPorIdExpoOperationCompleted == null)) {
                this.TraeEventosPorIdExpoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeEventosPorIdExpoOperationCompleted);
            }
            this.InvokeAsync("TraeEventosPorIdExpo", new object[] {
                        idExpo}, this.TraeEventosPorIdExpoOperationCompleted, userState);
        }
        
        private void OnTraeEventosPorIdExpoOperationCompleted(object arg) {
            if ((this.TraeEventosPorIdExpoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeEventosPorIdExpoCompleted(this, new TraeEventosPorIdExpoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TraeEventoPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EventoResponse TraeEventoPorId(int id) {
            object[] results = this.Invoke("TraeEventoPorId", new object[] {
                        id});
            return ((EventoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TraeEventoPorIdAsync(int id) {
            this.TraeEventoPorIdAsync(id, null);
        }
        
        /// <remarks/>
        public void TraeEventoPorIdAsync(int id, object userState) {
            if ((this.TraeEventoPorIdOperationCompleted == null)) {
                this.TraeEventoPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeEventoPorIdOperationCompleted);
            }
            this.InvokeAsync("TraeEventoPorId", new object[] {
                        id}, this.TraeEventoPorIdOperationCompleted, userState);
        }
        
        private void OnTraeEventoPorIdOperationCompleted(object arg) {
            if ((this.TraeEventoPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeEventoPorIdCompleted(this, new TraeEventoPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TraeStandsPorIdExpo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StandsResponse TraeStandsPorIdExpo(int idExpo) {
            object[] results = this.Invoke("TraeStandsPorIdExpo", new object[] {
                        idExpo});
            return ((StandsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TraeStandsPorIdExpoAsync(int idExpo) {
            this.TraeStandsPorIdExpoAsync(idExpo, null);
        }
        
        /// <remarks/>
        public void TraeStandsPorIdExpoAsync(int idExpo, object userState) {
            if ((this.TraeStandsPorIdExpoOperationCompleted == null)) {
                this.TraeStandsPorIdExpoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeStandsPorIdExpoOperationCompleted);
            }
            this.InvokeAsync("TraeStandsPorIdExpo", new object[] {
                        idExpo}, this.TraeStandsPorIdExpoOperationCompleted, userState);
        }
        
        private void OnTraeStandsPorIdExpoOperationCompleted(object arg) {
            if ((this.TraeStandsPorIdExpoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeStandsPorIdExpoCompleted(this, new TraeStandsPorIdExpoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TraeStandPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StandResponse TraeStandPorId(int id) {
            object[] results = this.Invoke("TraeStandPorId", new object[] {
                        id});
            return ((StandResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TraeStandPorIdAsync(int id) {
            this.TraeStandPorIdAsync(id, null);
        }
        
        /// <remarks/>
        public void TraeStandPorIdAsync(int id, object userState) {
            if ((this.TraeStandPorIdOperationCompleted == null)) {
                this.TraeStandPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeStandPorIdOperationCompleted);
            }
            this.InvokeAsync("TraeStandPorId", new object[] {
                        id}, this.TraeStandPorIdOperationCompleted, userState);
        }
        
        private void OnTraeStandPorIdOperationCompleted(object arg) {
            if ((this.TraeStandPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeStandPorIdCompleted(this, new TraeStandPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TraeSponsorsPorIdExpo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SponsorsResponse TraeSponsorsPorIdExpo(int idExpo) {
            object[] results = this.Invoke("TraeSponsorsPorIdExpo", new object[] {
                        idExpo});
            return ((SponsorsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TraeSponsorsPorIdExpoAsync(int idExpo) {
            this.TraeSponsorsPorIdExpoAsync(idExpo, null);
        }
        
        /// <remarks/>
        public void TraeSponsorsPorIdExpoAsync(int idExpo, object userState) {
            if ((this.TraeSponsorsPorIdExpoOperationCompleted == null)) {
                this.TraeSponsorsPorIdExpoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeSponsorsPorIdExpoOperationCompleted);
            }
            this.InvokeAsync("TraeSponsorsPorIdExpo", new object[] {
                        idExpo}, this.TraeSponsorsPorIdExpoOperationCompleted, userState);
        }
        
        private void OnTraeSponsorsPorIdExpoOperationCompleted(object arg) {
            if ((this.TraeSponsorsPorIdExpoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeSponsorsPorIdExpoCompleted(this, new TraeSponsorsPorIdExpoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TraeSponsorPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SponsorResponse TraeSponsorPorId(int id) {
            object[] results = this.Invoke("TraeSponsorPorId", new object[] {
                        id});
            return ((SponsorResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TraeSponsorPorIdAsync(int id) {
            this.TraeSponsorPorIdAsync(id, null);
        }
        
        /// <remarks/>
        public void TraeSponsorPorIdAsync(int id, object userState) {
            if ((this.TraeSponsorPorIdOperationCompleted == null)) {
                this.TraeSponsorPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraeSponsorPorIdOperationCompleted);
            }
            this.InvokeAsync("TraeSponsorPorId", new object[] {
                        id}, this.TraeSponsorPorIdOperationCompleted, userState);
        }
        
        private void OnTraeSponsorPorIdOperationCompleted(object arg) {
            if ((this.TraeSponsorPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraeSponsorPorIdCompleted(this, new TraeSponsorPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewUsuarioRequest {
        
        private string nombreField;
        
        private string apellidoField;
        
        private string empresaField;
        
        private string correoField;
        
        private string telefonoField;
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
            }
        }
        
        /// <remarks/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewContactoRequest {
        
        private int idUsuarioField;
        
        private string nombreField;
        
        private string empresaField;
        
        private string correoField;
        
        private string telefonoField;
        
        private System.DateTime fechaRegistroField;
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
            }
        }
        
        /// <remarks/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sponsors {
        
        private int idField;
        
        private int idExpoField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string uRLWebField;
        
        private string uRLFacebookField;
        
        private string uRLTwitterField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int IdExpo {
            get {
                return this.idExpoField;
            }
            set {
                this.idExpoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string URLWeb {
            get {
                return this.uRLWebField;
            }
            set {
                this.uRLWebField = value;
            }
        }
        
        /// <remarks/>
        public string URLFacebook {
            get {
                return this.uRLFacebookField;
            }
            set {
                this.uRLFacebookField = value;
            }
        }
        
        /// <remarks/>
        public string URLTwitter {
            get {
                return this.uRLTwitterField;
            }
            set {
                this.uRLTwitterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Stands {
        
        private int idField;
        
        private string nombreField;
        
        private int numeroStandField;
        
        private int idExpoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroStand {
            get {
                return this.numeroStandField;
            }
            set {
                this.numeroStandField = value;
            }
        }
        
        /// <remarks/>
        public int IdExpo {
            get {
                return this.idExpoField;
            }
            set {
                this.idExpoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Eventos {
        
        private int idField;
        
        private int idExpoField;
        
        private string nombreEventoField;
        
        private string descripcionField;
        
        private System.DateTime fechaField;
        
        private string nombreConferencistaField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int IdExpo {
            get {
                return this.idExpoField;
            }
            set {
                this.idExpoField = value;
            }
        }
        
        /// <remarks/>
        public string NombreEvento {
            get {
                return this.nombreEventoField;
            }
            set {
                this.nombreEventoField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string NombreConferencista {
            get {
                return this.nombreConferencistaField;
            }
            set {
                this.nombreConferencistaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Expos {
        
        private int idField;
        
        private string nombreField;
        
        private string calleField;
        
        private string numeroField;
        
        private string coloniaField;
        
        private string ciudadField;
        
        private string estadoField;
        
        private string paisField;
        
        private string longitudField;
        
        private string latitudField;
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinalField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
            }
        }
        
        /// <remarks/>
        public string Ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        public string Longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
            }
        }
        
        /// <remarks/>
        public string Latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaFinal {
            get {
                return this.fechaFinalField;
            }
            set {
                this.fechaFinalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Contactos {
        
        private int idField;
        
        private int idUsuarioField;
        
        private string nombreField;
        
        private string correoField;
        
        private string empresaField;
        
        private string telefonoField;
        
        private System.DateTime fechaRegistroField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <remarks/>
        public string Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
            }
        }
        
        /// <remarks/>
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario {
        
        private int idField;
        
        private string nombreField;
        
        private string correoField;
        
        private string empresaField;
        
        private System.DateTime fechaRegistroField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <remarks/>
        public string Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SponsorResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SponsorsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StandResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StandsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EventoResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EventosResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExpoResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExposResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactosResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactoResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UsuarioResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseBase {
        
        private bool successField;
        
        private string messageField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SponsorResponse : ResponseBase {
        
        private Sponsors sponsorField;
        
        /// <remarks/>
        public Sponsors Sponsor {
            get {
                return this.sponsorField;
            }
            set {
                this.sponsorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SponsorsResponse : ResponseBase {
        
        private Sponsors[] sponsorsField;
        
        /// <remarks/>
        public Sponsors[] Sponsors {
            get {
                return this.sponsorsField;
            }
            set {
                this.sponsorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StandResponse : ResponseBase {
        
        private Stands standField;
        
        /// <remarks/>
        public Stands Stand {
            get {
                return this.standField;
            }
            set {
                this.standField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StandsResponse : ResponseBase {
        
        private Stands[] standsField;
        
        /// <remarks/>
        public Stands[] Stands {
            get {
                return this.standsField;
            }
            set {
                this.standsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EventoResponse : ResponseBase {
        
        private Eventos eventoField;
        
        /// <remarks/>
        public Eventos Evento {
            get {
                return this.eventoField;
            }
            set {
                this.eventoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EventosResponse : ResponseBase {
        
        private Eventos[] eventosField;
        
        /// <remarks/>
        public Eventos[] Eventos {
            get {
                return this.eventosField;
            }
            set {
                this.eventosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExpoResponse : ResponseBase {
        
        private Expos expoField;
        
        /// <remarks/>
        public Expos Expo {
            get {
                return this.expoField;
            }
            set {
                this.expoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExposResponse : ResponseBase {
        
        private Expos[] exposField;
        
        /// <remarks/>
        public Expos[] Expos {
            get {
                return this.exposField;
            }
            set {
                this.exposField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactosResponse : ResponseBase {
        
        private Contactos[] contactosField;
        
        /// <remarks/>
        public Contactos[] Contactos {
            get {
                return this.contactosField;
            }
            set {
                this.contactosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContactoResponse : ResponseBase {
        
        private Contactos contactoField;
        
        /// <remarks/>
        public Contactos Contacto {
            get {
                return this.contactoField;
            }
            set {
                this.contactoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioResponse : ResponseBase {
        
        private Usuario usuarioField;
        
        /// <remarks/>
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RegistrarUsuarioCompletedEventHandler(object sender, RegistrarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TraeUsuarioPorIdCompletedEventHandler(object sender, TraeUsuarioPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeUsuarioPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeUsuarioPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TraeUsuarioPorCorreoCompletedEventHandler(object sender, TraeUsuarioPorCorreoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeUsuarioPorCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeUsuarioPorCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsuarioResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsuarioResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RegistrarContactoCompletedEventHandler(object sender, RegistrarContactoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarContactoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarContactoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ContactoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ContactoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TraeContactosPorIdUsuarioCompletedEventHandler(object sender, TraeContactosPorIdUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeContactosPorIdUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeContactosPorIdUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ContactosResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ContactosResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TraeContactoPorIdCompletedEventHandler(object sender, TraeContactoPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeContactoPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeContactoPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ContactoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ContactoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TraeAllExposCompletedEventHandler(object sender, TraeAllExposCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeAllExposCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeAllExposCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExposResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExposResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TraeExpoPorIdCompletedEventHandler(object sender, TraeExpoPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeExpoPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeExpoPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExpoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExpoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TraeEventosPorIdExpoCompletedEventHandler(object sender, TraeEventosPorIdExpoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeEventosPorIdExpoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeEventosPorIdExpoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EventosResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EventosResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TraeEventoPorIdCompletedEventHandler(object sender, TraeEventoPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeEventoPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeEventoPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EventoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EventoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TraeStandsPorIdExpoCompletedEventHandler(object sender, TraeStandsPorIdExpoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeStandsPorIdExpoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeStandsPorIdExpoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StandsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StandsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TraeStandPorIdCompletedEventHandler(object sender, TraeStandPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeStandPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeStandPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StandResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StandResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TraeSponsorsPorIdExpoCompletedEventHandler(object sender, TraeSponsorsPorIdExpoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeSponsorsPorIdExpoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeSponsorsPorIdExpoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SponsorsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SponsorsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TraeSponsorPorIdCompletedEventHandler(object sender, TraeSponsorPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraeSponsorPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraeSponsorPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SponsorResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SponsorResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591